### ISSUE TITLE
Replace redisearch python package with redis >= 4.0.0

### ISSUE THREAD

**Issue by nathanweeks** [legumeinfo/microservices#39] opened 2022-01-08 23:14 UTC
Per the RediSearch/redisearch-py repo, the redisearch python package [has been deprecated as of redis-py 4.0.0](https://github.com/RediSearch/redisearch-py#deprecation-notice), as its functionality was absorbed into the latter. Will need to get on the bandwagon at some point and make the switch in this repo.

**Comment by alancleary** [comment] 2022-01-10 16:42
Thanks for creating an issue, Nathan. I hadn't noticed the deprecation notice.

Looking at the redis-py source, it looks like they basically copy-pasted the redisearch library in as a module, so migrating shouldn't be too difficult, in theory. Unfortunately, it looks like there still isn't support for aio, so my little aio shim layer will have to remain. Maybe I'll create an issue in the redis-py repo for this...

**Comment by alancleary** [comment] 2022-03-16 20:15
Apparently redis-py is [also absorbing aioredis](https://github.com/aio-libs/aioredis-py) (one library to rule them all!). This will be official in [the imminent 4.2.0 release](https://github.com/redis/redis-py/releases), so I'll hold off on tackling this issue until 4.2.0 is out. In the meantime I'll open an issue on redis-py about whether or not the absorbed redisearch module will work with the aioredis client once its assimilation is complete.

**Comment by alancleary** [comment] 2022-03-23 15:18
[Release 4.2.0](https://github.com/redis/redis-py/releases/tag/v4.2.0) is out! I'll get going on this as soon as I can.

I opened [an issue](https://github.com/redis/redis-py/issues/2053) regarding aio support within the RediSearch module and the initial response suggested that it may be a while before they have integration. Oh well. Our aio wrapper works just fine so this issue can move ahead with that.

**Comment by alancleary** [comment] 2022-06-03 00:56
The redisearch-py authors confirmed in the issue I previously mentioned that support for aio was added to the redis-yp redisearch module in release 4.3.1, meaning this work can now include removing our custom aio wrapper for redisearch.

**Comment by alancleary** [comment] 2022-07-14 19:20
Updated the chromosome service in commit 7f097e78a2ab7d88dda5d03b86477f6c23be78cf.

**Comment by alancleary** [comment] 2022-07-14 19:34
Updated the micro-synteny search service in commit 3060d3d6fadba25e556c1545513f610d5e12853b.

**Comment by alancleary** [comment] 2022-07-14 19:46
Updated the pairwise macro-synteny blocks service in commit bd81a24f5dca24370dea64bfcbf93c80781a6b95.

**Comment by alancleary** [comment] 2022-07-14 21:58
Updated the macro-synteny service in commit f8680adb63ade23184c5fb790be760e0f1a7a639.

**Comment by alancleary** [comment] 2022-07-14 22:09
Updated the gene search service in commit 1a30d3876ffffeeadc1f09bc79e6ae645ebbc3f6.

**Comment by alancleary** [comment] 2022-07-14 22:15
Updated the chromosome region service in commit 026cb2ff3fd2c908bec9f3b0bed1675dff72e41b.

**Comment by alancleary** [comment] 2022-07-14 22:22
Updated the chromosome search service in commit 3fcb0de8d64e7cb3504369e9958db1e7bea3cebb.

**Comment by alancleary** [comment] 2022-07-14 22:28
I removed the aioredis dependency from the search service in commit 68067a8ef883bab2451af9226f90336d9f798649. I did not replace it with the redis package because the service isn't actually using redis!

**Comment by alancleary** [comment] 2022-07-15 18:50
All Python packages have been updated to redis 4+. Closing.

**Closed by alancleary** 2022-07-15 18:50 UTC
Labels: enhancement
